In [ ]:
# 데이터 연결하기
# 데이터 결측치 확인하기
# 결측 데이터 처리하기
# 그래프 구현하기

In [21]:
# 데이터 연결하기
# 라이브러리 불러오기
import pandas as pd
import matplotlib.pyplot as plt

# Excel 데이터를 데이터프레임 변환 
df = pd.read_excel('C:\\김지은\\파이썬_src\\pandas-data-analysis\\part4\\data\\시도별_전출입_인구수.xlsx')
# 해당 파일경로를 입력할때 경로복사 및 입력 잘해두고,
# 한국어는 되도록이면 쓰지말고, 역슬래시 두번 사용하기 \\

# 이러는 이유
# \n → 줄바꿈
# \t → 탭
# 이런 식으로 해석되기 때문이다.

# 일반적인/ 슬래시의 경우에는 그런걸 염두하지않아도 되어서, / 하나만 입력해도 된다.

# 데이터 확인
df.head(5)

,전출지별,전입지별,1970,1971,1972,1973,1974,1975,1976,1977,...,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017
0,전출지별,전입지별,이동자수 (명),이동자수 (명),이동자수 (명),이동자수 (명),이동자수 (명),이동자수 (명),이동자수 (명),이동자수 (명),...,이동자수 (명),이동자수 (명),이동자수 (명),이동자수 (명),이동자수 (명),이동자수 (명),이동자수 (명),이동자수 (명),이동자수 (명),이동자수 (명)
1,전국,전국,4046536,4210164,3687938,4860418,5297969,9011440,6773250,7397623,...,8808256,8487275,8226594,8127195,7506691,7411784,7629098,7755286,7378430,7154226
2,NaN,서울특별시,1742813,1671705,1349333,1831858,2050392,3396662,2756510,2893403,...,2025358,1873188,1733015,1721748,1555281,1520090,1573594,1589431,1515602,1472937
3,NaN,부산광역시,448577,389797,362202,482061,680984,805979,724664,785117,...,514502,519310,519334,508043,461042,478451,485710,507031,459015,439073
4,NaN,대구광역시,-,-,-,-,-,-,-,-,...,409938,398626,370817,370563,348642,351873,350213,351424,328228,321182

In [ ]:
# 결측치란?
# 결측치 : 다양한 이유로 불완전한 데이터 - 누락 None NaN '' 데이터 없음
# 1. 제거 - 데이터가 충분해서 해당 결측치 해당 데이터를 삭제해도 충분할때..
# 2. 보간
    # 단순 실수로 누락되어서 뻔히 어떤 값인지 알 수 있을 때
    # 결측치가 전체 데이터 대비 적다.. 대략 15% 미만이고, 데이터가 적어서 살려야 할때 - 평균, 표준편차, 빈도수 등 다양하게 채움
    # 보간기법이라고 함 --> 자체 머신러닝을 이용해서 해당부분의 값을 예측

# 이게 인공지능의 질을 정하기도한다?
# 결측치를 어떻게 처리하느냐에 따라서 인공지능의 질이 좌우된다고 한다.
# 결측치 처리 = 데이터 전처리의 핵심 단계이고, 이게 모델의 "질"을 크게 좌우해요.
# 데이터 과학에서는 “Garbage in, garbage out”이라는 말도 있죠. (데이터 품질이 나쁘면 모델도 나빠진다).
# 예를 들어:
# 평균으로 단순히 채웠다면 → 데이터의 분산이 줄어들어서 모델이 덜 민감해질 수 있음. -> 더 상세한 데이터 조회가 어려움
# 적절한 보간법을 썼다면 → 원래 데이터의 패턴을 더 잘 보존할 수 있음.
# 잘채울려면? 어떻게 해야될까?
# https://chatgpt.com/s/t_68dba8edf62081918686500cd1dd0963

In [ ]:
# 데이터 결측치 확인하기
# 직접확인
# 간단히 확인: info(), describe()
# 정확히 확인: isna().sum(), isna().mean()
# 시각화: missingno

In [23]:
# 직접확인
# 전출지별 에서 항목이 전국만 있는지 확인하는 방법
print(df['전출지별']) # 직접 확인하기에는 중간에 생략된부분을 확인 할수가 없다.
print('*'*60)
print(df['전출지별'].value_counts()) # 그래서 해당 컬럼의 종목의 갯수와 목록을 조회

# 컬럼의 값들이 전국 외에도 다른 컬럼(서울특별시, 부산광역시, 대구광역시.. 등)들이 1씩 조회된걸 확인,
# 아래 ... 사이에 다른컬럼들이 포함되어있다는 것을 알 수 있다.

# value_counts()
# 시리즈 객체가 제공하는 메서드
# 시리즈(Series) 혹은 특정 컬럼(데이터프레임에 비롯한 시리즈)의 값들이
# 몇 번 등장했는지 세어서 빈도표(frequency table)로 반환하는 메서드

# value
# 시리즈와 데이터 프레임의 값들을 NumPy 배열(ndarray) 형태로 반환하는 속성
# 넘파이 배열 :
# 리스트와 비슷하게 여러 값들을 담을 수 있는 구조이다.
# 하지만 파이썬 리스트보다 더 빠르고 메모리를 덜 쓰면서 수학/통계/행렬 연산을 할 수 있다.
# 한 배열 안에는 모든 원소가 같은 자료형(int, float 등)이어야 한다.

0      전출지별
1        전국
2       NaN
3       NaN
4       NaN
       ...
320     NaN
321     NaN
322     NaN
323     NaN
324     NaN
Name: 전출지별, Length: 325, dtype: object
************************************************************
전출지별
전출지별       1
전국         1
서울특별시      1
부산광역시      1
대구광역시      1
인천광역시      1
광주광역시      1
대전광역시      1
울산광역시      1
세종특별자치시    1
경기도        1
강원도        1
충청북도       1
충청남도       1
전라북도       1
전라남도       1
경상북도       1
경상남도       1
제주특별자치도    1
Name: count, dtype: int64

In [ ]:
# 정확히 확인: isna().sum(), isna().mean()
# 시각화: missingno

In [ ]:
# 여기서는 누락된 정보를 삭제하는 방법 보다는 채울 내용이 존재하기때문에,
# 그리고 누락된 데이터를 다 삭제하면 많은 데이터가 날라가기도 하므로
# dropna()가 아닌 ffill() 사용

# 누락값(NaN)을 앞 데이터로 채움 (엑셀 양식 병합 부분)
df = df.ffill()
df.head()

In [ ]:
# 결측치 제거 dropna()
# dropna() : 결측데이터가 포함된 행 또는 열을 제거한다.
# 행을 제거 : axis = 0 (기본값)
# 열을 제거 : axis = 1
# how='any' → 하나라도 NaN 있으면 삭제 (기본값)
# how = 'all' : 모든 값이 결측치일때 삭제
# thresh : 결측치가 아닌값의 최소개수
# 지정한 개수 이상으로 값이 채워져 있는 행/열만 남기고, 그렇지 않으면 삭제
df.dropna(thresh = 2, axis = 1) # 2개 이상의 데이터가 있는 경우에는 남긴다. 그 미만 1혹은 0의 결측데이터는 삭제한다.
                                # 해당하는 열을 제거한다.
df.dropna(how = 'all') # 모든값이 결측치일때 삭제한다.
df.dropna(thresh = 2) # 2개 이상의 데이터가 있는 경우에는 남긴다. 그 미만 1혹은 0의 결측데이터는 삭제한다.

In [24]:
# 결측치 대체
# ffill() : 결측치를 직전 값으로 채운다.
# ffill = forward fill = 위쪽(이전 행)의 값을 그대로 가져와 채운다.
# 시계열 데이터, 순서가 있는 데이터에서 자주 사용
# axis : 결측치를 채울 방향, 앞에 있는 값으로 채운다. -> 그럼 반대는? bfill()
# axis=0 → 위쪽 값으로 채움 (행 기준, 기본값)
# axis=1 → 왼쪽 값으로 채움 (열 기준)
# limit : 연속된 결측치 중 몇 개까지만 채울지 지정
import numpy as np

df2 = pd.DataFrame({
    'A':[1, np.nan, np.nan, 4],
    'B':[np.nan, 2, np.nan, 3]
})

print(df2)
print(df2.ffill())                # 위쪽 값으로 채움
print(df2.ffill(limit=1))         # 연속된 NaN 중 1개만 채움 #^
print(df2.ffill(axis=1))          # 행 기준으로 왼쪽 값으로 채움

# bfill() : 결측치를 뒤쪽(다음 값) 으로 채운다.
# axis : ffill()과 반대이다. 뒤에 있는 값으로 채운다.
# axis=0 → 아래쪽 값으로 채움 (행 기준, 기본값)
# axis=1 → 오른쪽 값으로 채움 (열 기준)
# limit : 연속된 결측치 중 몇 개까지만 채울지 지정

     A    B
0  1.0  NaN
1  NaN  2.0
2  NaN  NaN
3  4.0  3.0
     A    B
0  1.0  NaN
1  1.0  2.0
2  1.0  2.0
3  4.0  3.0
     A    B
0  1.0  NaN
1  1.0  2.0
2  NaN  2.0
3  4.0  3.0
     A    B
0  1.0  1.0
1  NaN  2.0
2  NaN  NaN
3  4.0  3.0

In [15]:
print(df2)
print(df2.bfill())                # 아래쪽 값으로 채움
print(df2.bfill(limit=1))         # 연속된 NaN 중 1개만 채움 #^
print(df2.bfill(axis=1))          # 행 기준으로 왼쪽 값으로 채움

     A    B
0  1.0  NaN
1  NaN  2.0
2  NaN  NaN
3  4.0  3.0
     A    B
0  1.0  2.0
1  4.0  2.0
2  4.0  3.0
3  4.0  3.0
     A    B
0  1.0  2.0
1  NaN  2.0
2  4.0  3.0
3  4.0  3.0
     A    B
0  1.0  NaN
1  2.0  2.0
2  NaN  NaN
3  4.0  3.0

In [ ]:
# fillna : 특정 값을 지정하여 그걸로 채운다.

df2.fillna(0) # 빈값을 0으로 채운다.
print(f'각 컬럼의 평균값 \n {df2.mean()}')
df2.fillna(df2.mean()) # 해당 컬럼의 평균 값으로 채운다.
                       # 그외 넣는 값들 정리 : .mean(), .max(), .min(), .median(),.mode()
                                            # 평균, 최대값, 최소값, 중간값, 최빈값
df2.fillna(method = 'ffill') # bfill
# DataFrame.fillna(
#     value=None,      # 단일 값, dict, Series 등으로 결측치 대체 - ()안에 그냥 입력하면 여기로 들어간다.
#     method=None,     # 'ffill' or 'bfill' : 앞/뒤 값으로 채우기
#     axis=None,       # 0=행, 1=열
#     inplace=False,   # True면 원본 변경, False면 새 DataFrame 반환
#     limit=None,      # 채우는 최대 개수
#     downcast=None    # 데이터 타입 변환 옵션
        # 데이터 타입을 임의로 변환가능하게 한 이유,
        # pandas는 컬럼 단위로 데이터 타입(dtype)을 관리하기 때문에,
        # 컬럼 안에 있는 하나의 값이 다른 타입이면 전체 컬럼의 타입이 바뀔 수 있기때문이다.
        # 예시 : 원래 int였는데 문자열이 들어오면서 object 타입이 되어버리는 경우
        #        들어가는 값의 계산으로 인해서 int였던 판다스 객체가 float가 되어버리는 경우
        # downcast=None → 아무 타입 변환 안 함
        # downcast='int' → 정수형으로 변환
        # downcast='float' → 실수형으로 변환
        # downcast='infer' → 자동으로 적절한 타입 추측
# )

갓 컬럼의 평균값
 A    2.5
B    2.5
dtype: float64

C:\Users\Playdata2\AppData\Local\Temp\ipykernel_15080\1698897030.py:8: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df2.fillna(method = 'ffill') # bfill

     A    B
0  1.0  NaN
1  1.0  2.0
2  1.0  2.0
3  4.0  3.0

In [ ]:
# 결측치 대처
# 보간 기법 interpolate
# 데이터 흐름 기반 추정
# 결측치가 있을 때 앞뒤 값, 선형, 다항식 등으로 값을 예측해서 채운다.
# 시계열 데이터나 연속형 수치 데이터에서 자주 사용한다.

# method : 보간 방식 지정 ('linear', 'time', 'index', 'polynomial' 등)
# 예시 : https://chatgpt.com/share/68dbb744-e05c-8012-980e-95abc2f28a62
# axis : 0=행, 1=열
# limit	: 최대 몇 개의 NaN을 채울지
# inplace : True면 원본 수정, False면 새 객체 반환
# order : 다항식 보간 시 차수 지정 (method='polynomial')
# limit_direction : 'forward'/'backward'/'both' 채우기 방향

0    10.0
1     NaN
2    30.0
3     NaN
4    50.0
dtype: float64

0    10.0
1    20.0
2    30.0
3    40.0
4    50.0
dtype: float64