In [56]:
import pandas as pd

# Timestamp의 배열 만들기 - 월 간격, 월의 시작일 기준
ts_ms = pd.date_range(start='2025-01-01',
                end= '2025-10-02',
                periods=100,
                # freq = 'MS',
                tz ='Asia/Seoul')

# print(ts_ms)
data = {'date' : ts_ms.strftime('%Y-%m-%d')}
df = pd.DataFrame(data)

df['date'] = pd.to_datetime(df.date) # ^
# df.date의 데이터 문자열을 **DatetimeIndex**로 변환 하여 df['date']에 넣는다.

# 년도를 추출해서 새로운 컬럼으로 넣기
df.info()
df['year'] = df.date.dt.year
df['month'] = df.date.dt.month
df['day_int'] = df.date.dt.weekday # 0 월요일

#이렇게 하면 df['date'] 컬럼만 datetime64[ns] 타입이 됩니다.
# datetime64[ns] 타입은 DatetimeIndex에서 사용하는 속성들(.year, .month, .weekday 등) 을 컬럼에서도 쓸 수 있게 해줍니다.

def convert_week(x):
    temp = ['월','화','수','목','금','토','일']
    return temp[x]
df['day_str'] = df['day_int'].apply(lambda x : convert_week(x))

# 주말(토일)은 1 나머지는 0
# 강사님 풀이
df['day_weekend'] = df['day_str'].apply(lambda x : 1 if x in ['토','일'] else 0)
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    100 non-null    datetime64[ns]
dtypes: datetime64[ns](1)
memory usage: 932.0 bytes

        date  year  month  day_int day_str  day_weekend
0 2025-01-01  2025      1        2       수            0
1 2025-01-03  2025      1        4       금            0
2 2025-01-06  2025      1        0       월            0
3 2025-01-09  2025      1        3       목            0
4 2025-01-12  2025      1        6       일            1

In [57]:
%pip install holidays

Requirement already satisfied: holidays in c:\김지은\파이썬_src\.venv\lib\site-packages (0.81)
Requirement already satisfied: python-dateutil in c:\김지은\파이썬_src\.venv\lib\site-packages (from holidays) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in c:\김지은\파이썬_src\.venv\lib\site-packages (from python-dateutil->holidays) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [58]:
import holidays
kr_holidays = holidays.KR(years = [2025])
kr_holidays.append({'2025-10-10':'휴강'})
kr_holidays = sorted(kr_holidays.items(), key = lambda x : x[0])
for key, value in kr_holidays:
    print(f'{key} : {value}')
print(kr_holidays
      )

2025-01-01 : 신정연휴
2025-01-27 : 임시공휴일
2025-01-28 : 설날 전날
2025-01-29 : 설날
2025-01-30 : 설날 다음날
2025-03-01 : 삼일절
2025-03-03 : 삼일절 대체 휴일
2025-05-05 : 부처님오신날; 어린이날
2025-05-06 : 부처님오신날 대체 휴일; 어린이날 대체 휴일
2025-06-03 : 대통령 선거일
2025-06-06 : 현충일
2025-08-15 : 광복절
2025-10-03 : 개천절
2025-10-05 : 추석 전날
2025-10-06 : 추석
2025-10-07 : 추석 다음날
2025-10-08 : 추석 대체 휴일
2025-10-09 : 한글날
2025-10-10 : 휴강
2025-12-25 : 기독탄신일
[(datetime.date(2025, 1, 1), '신정연휴'), (datetime.date(2025, 1, 27), '임시공휴일'), (datetime.date(2025, 1, 28), '설날 전날'), (datetime.date(2025, 1, 29), '설날'), (datetime.date(2025, 1, 30), '설날 다음날'), (datetime.date(2025, 3, 1), '삼일절'), (datetime.date(2025, 3, 3), '삼일절 대체 휴일'), (datetime.date(2025, 5, 5), '부처님오신날; 어린이날'), (datetime.date(2025, 5, 6), '부처님오신날 대체 휴일; 어린이날 대체 휴일'), (datetime.date(2025, 6, 3), '대통령 선거일'), (datetime.date(2025, 6, 6), '현충일'), (datetime.date(2025, 8, 15), '광복절'), (datetime.date(2025, 10, 3), '개천절'), (datetime.date(2025, 10, 5), '추석 전날'), (datetime.date(2025, 10, 6), '추석'), (datetime.date(2025, 10, 7), '추석 다음날'), (datetime.date(2025, 10, 8), '추석 대체 휴일'), (datetime.date(2025, 10, 9), '한글날'), (datetime.date(2025, 10, 10), '휴강'), (datetime.date(2025, 12, 25), '기독탄신일')]

In [59]:
# df['is_holiday'] =

In [60]:
# 강사님 풀이
df['date'] # datetime64
kr_holidays # datetime.date
df['date'].dt.date[0]
df['is_holiday'] = df['date'].dt.date.isin([a for a,b in kr_holidays]).astype(int)
df.head()

        date  year  month  day_int day_str  day_weekend  is_holiday
0 2025-01-01  2025      1        2       수            0           1
1 2025-01-03  2025      1        4       금            0           0
2 2025-01-06  2025      1        0       월            0           0
3 2025-01-09  2025      1        3       목            0           0
4 2025-01-12  2025      1        6       일            1           0

In [61]:
# 학생 풀이 1트 ^ gpt
# 위 holiday 객체 들을 클래스 에 넣어서, isinstance()로 구별하여 True, False값을 반환하기
class ItsHoliday:
    def __init__(self, date, name):
        self.date = date
        self.name = name

# 순환문으로 클래스 객체로 변환
for i in range(len(kr_holidays)):
    kr_holidays[i] = ItsHoliday(date, name)
# kr_holidays = [ItsHoliday(date, name) for date, name in kr_holidays]

# 확인
for h in kr_holidays:
    print(h.date, h.name, isinstance(h, ItsHoliday))

2025-12-25 기독탄신일 True
2025-12-25 기독탄신일 True
2025-12-25 기독탄신일 True
2025-12-25 기독탄신일 True
2025-12-25 기독탄신일 True
2025-12-25 기독탄신일 True
2025-12-25 기독탄신일 True
2025-12-25 기독탄신일 True
2025-12-25 기독탄신일 True
2025-12-25 기독탄신일 True
2025-12-25 기독탄신일 True
2025-12-25 기독탄신일 True
2025-12-25 기독탄신일 True
2025-12-25 기독탄신일 True
2025-12-25 기독탄신일 True
2025-12-25 기독탄신일 True
2025-12-25 기독탄신일 True
2025-12-25 기독탄신일 True
2025-12-25 기독탄신일 True
2025-12-25 기독탄신일 True

In [62]:
import datetime
# 휴일 확인 함수
def check_holidays(dates, holiday_list):
    """
    dates: datetime.date 객체 리스트
    holiday_list: ItsHoliday 객체 리스트
    return: [(date, True/False, 휴일 이름 or None), ...]
    """
    results = []
    for d in dates:
        found = False
        for h in holiday_list:
            if h.date == d:
                results.append((d, True, h.name))
                found = True
                break
        if not found:
            results.append((d, False, None))
    return results

# 사용자 입력
user_input = input("확인할 날짜를 YYYY-MM-DD 형식으로 ,(콤마)로 구분해 입력하세요: ")
# 예: 2025-01-01,2025-01-02,2025-01-28

# 문자열 분리
date_strings = user_input.split(",")

# datetime.date 객체로 변환
dates_to_check = [datetime.datetime.strptime(ds.strip(), "%Y-%m-%d").date() for ds in date_strings]

results = check_holidays(dates_to_check, kr_holidays)

for r in results:
    print(r)

(datetime.date(2025, 10, 2), False, None)