In [22]:
# 라이브러리 불러오기
import pandas as pd
import seaborn as sns

# # titanic 데이터셋 로딩
titanic_tips = sns.load_dataset('tips')
titanic_tips
# 행 인덱스 0~9 범위에서 age, fare 2개 열을 선택하여 데이터프레임 만들기
tdf = titanic_tips.loc[0:9, ['tip','total_bill','day','time','size']]

# 데이터프레임 출력
tdf

    tip  total_bill  day    time  size
0  1.01       16.99  Sun  Dinner     2
1  1.66       10.34  Sun  Dinner     3
2  3.50       21.01  Sun  Dinner     3
3  3.31       23.68  Sun  Dinner     2
4  3.61       24.59  Sun  Dinner     4
5  4.71       25.29  Sun  Dinner     4
6  2.00        8.77  Sun  Dinner     2
7  3.12       26.88  Sun  Dinner     4
8  1.96       15.04  Sun  Dinner     2
9  3.23       14.78  Sun  Dinner     2

In [23]:
tdf.query('total_bill > 14 and tip < 2')

    tip  total_bill  day    time  size
0  1.01       16.99  Sun  Dinner     2
8  1.96       15.04  Sun  Dinner     2

In [26]:
# 주말(Fri,Sat,Sun)
tdf.query("(day in ('Fri','Sat','Sun')) and (time == 'Dinner' and size >= 3)")

    tip  total_bill  day    time  size
1  1.66       10.34  Sun  Dinner     3
2  3.50       21.01  Sun  Dinner     3
4  3.61       24.59  Sun  Dinner     4
5  4.71       25.29  Sun  Dinner     4
7  3.12       26.88  Sun  Dinner     4

In [4]:
# 나이가 20세 이상이고 요금이 15 미만인 조건을 모두 충족하는 행을 필터링
df.query('age >= 20 and fare < 15')

    age     fare
0  22.0   7.2500
2  26.0   7.9250
4  35.0   8.0500
8  27.0  11.1333

In [4]:
# 나이가 20세 이상 또는 요금이 15 미만인 조건을 하나라도 충족하는 행을 필터링
df.query('age >= 20 or fare < 15')

    age     fare
0  22.0   7.2500
1  38.0  71.2833
2  26.0   7.9250
3  35.0  53.1000
4  35.0   8.0500
5   NaN   8.4583
6  54.0  51.8625
8  27.0  11.1333