##### 데이터 불러오기

In [21]:
import pandas as pd
df = pd.read_csv("C:\김지은\파이썬_src\pandas-data-analysis\part7\data\San-Francisco-Crime.csv")

df.head()

<>:2: SyntaxWarning: invalid escape sequence '\p'
<>:2: SyntaxWarning: invalid escape sequence '\p'
C:\Users\Playdata2\AppData\Local\Temp\ipykernel_10572\3894370419.py:2: SyntaxWarning: invalid escape sequence '\p'
  df = pd.read_csv("C:\김지은\파이썬_src\pandas-data-analysis\part7\data\San-Francisco-Crime.csv")

,Dates,Category,Descript,DayOfWeek,PdDistrict,Resolution,Address,X,Y
0,2015-05-13 23:53:00,WARRANTS,WARRANT ARREST,Wednesday,NORTHERN,"ARREST, BOOKED",OAK ST / LAGUNA ST,-122.425892,37.774599
1,2015-05-13 23:53:00,OTHER OFFENSES,TRAFFIC VIOLATION ARREST,Wednesday,NORTHERN,"ARREST, BOOKED",OAK ST / LAGUNA ST,-122.425892,37.774599
2,2015-05-13 23:33:00,OTHER OFFENSES,TRAFFIC VIOLATION ARREST,Wednesday,NORTHERN,"ARREST, BOOKED",VANNESS AV / GREENWICH ST,-122.424363,37.800414
3,2015-05-13 23:30:00,LARCENY/THEFT,GRAND THEFT FROM LOCKED AUTO,Wednesday,NORTHERN,NONE,1500 Block of LOMBARD ST,-122.426995,37.800873
4,2015-05-13 23:30:00,LARCENY/THEFT,GRAND THEFT FROM LOCKED AUTO,Wednesday,PARK,NONE,100 Block of BRODERICK ST,-122.438738,37.771541

##### 데이터 조회

In [22]:
df.shape

(878049, 9)

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 878049 entries, 0 to 878048
Data columns (total 9 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   Dates       878049 non-null  object
 1   Category    878049 non-null  object
 2   Descript    878049 non-null  object
 3   DayOfWeek   878049 non-null  object
 4   PdDistrict  878049 non-null  object
 5   Resolution  878049 non-null  object
 6   Address     878049 non-null  object
 7   X           878049 non-null  float64
 8   Y           878049 non-null  float64
dtypes: float64(2), object(7)
memory usage: 60.3+ MB

In [24]:
# # Domain 지식   컬럼정보
# Dates: 범죄 사건이 발생한 날짜와 시간 (타임스탬프)

# Category: 범죄 사건의 유형 ( 예측해야 할 목표 변수)

# Descript: 범죄 사건에 대한 상세한 설명

# DayOfWeek: 요일

# PdDistrict: 경찰서 관할 구역명

# Resolution: 사건이 어떻게 해결되었는지에 대한 정보

# Address: 범죄 사건이 발생한 대략적인 주소

# X: 경도 (Longitude)

# Y: 위도 (Latitude)

##### 데이터 전처리

In [25]:
# 불필요한 컬럼제거
train = df.drop(columns=['Descript','Resolution','Address'])
train.head()

,Dates,Category,DayOfWeek,PdDistrict,X,Y
0,2015-05-13 23:53:00,WARRANTS,Wednesday,NORTHERN,-122.425892,37.774599
1,2015-05-13 23:53:00,OTHER OFFENSES,Wednesday,NORTHERN,-122.425892,37.774599
2,2015-05-13 23:33:00,OTHER OFFENSES,Wednesday,NORTHERN,-122.424363,37.800414
3,2015-05-13 23:30:00,LARCENY/THEFT,Wednesday,NORTHERN,-122.426995,37.800873
4,2015-05-13 23:30:00,LARCENY/THEFT,Wednesday,PARK,-122.438738,37.771541

In [26]:
# 범주형 데이터 변환
# 종속변수 Category 인코딩
from sklearn.preprocessing import LabelEncoder
LabelEncoder().fit_transform(train.Category)
train.head()

,Dates,Category,DayOfWeek,PdDistrict,X,Y
0,2015-05-13 23:53:00,WARRANTS,Wednesday,NORTHERN,-122.425892,37.774599
1,2015-05-13 23:53:00,OTHER OFFENSES,Wednesday,NORTHERN,-122.425892,37.774599
2,2015-05-13 23:33:00,OTHER OFFENSES,Wednesday,NORTHERN,-122.424363,37.800414
3,2015-05-13 23:30:00,LARCENY/THEFT,Wednesday,NORTHERN,-122.426995,37.800873
4,2015-05-13 23:30:00,LARCENY/THEFT,Wednesday,PARK,-122.438738,37.771541

In [27]:
# 경찰러 관할 구역 PdDistrict - oneHot
district_dummies = pd.get_dummies(train.PdDistrict,prefix='District')

# 합치기
train = pd.concat([train,district_dummies],axis=1)
train = train.drop(columns=['PdDistrict'])
train.head()

,Dates,Category,DayOfWeek,X,Y,District_BAYVIEW,District_CENTRAL,District_INGLESIDE,District_MISSION,District_NORTHERN,District_PARK,District_RICHMOND,District_SOUTHERN,District_TARAVAL,District_TENDERLOIN
0,2015-05-13 23:53:00,WARRANTS,Wednesday,-122.425892,37.774599,False,False,False,False,True,False,False,False,False,False
1,2015-05-13 23:53:00,OTHER OFFENSES,Wednesday,-122.425892,37.774599,False,False,False,False,True,False,False,False,False,False
2,2015-05-13 23:33:00,OTHER OFFENSES,Wednesday,-122.424363,37.800414,False,False,False,False,True,False,False,False,False,False
3,2015-05-13 23:30:00,LARCENY/THEFT,Wednesday,-122.426995,37.800873,False,False,False,False,True,False,False,False,False,False
4,2015-05-13 23:30:00,LARCENY/THEFT,Wednesday,-122.438738,37.771541,False,False,False,False,False,True,False,False,False,False

In [31]:
train['Year'] = pd.to_datetime(train.Dates).dt.year
train['Month'] = pd.to_datetime(train.Dates).dt.month
train['Day'] = pd.to_datetime(train.Dates).dt.day
train['Hour'] = pd.to_datetime(train.Dates).dt.hour
train['Minute'] = pd.to_datetime(train.Dates).dt.minute

# 요일 정보
# one hot
dayofweek_onehot = pd.get_dummies(train.DayOfWeek,prefix='Day').astype(int)
pd.concat([train,dayofweek_onehot],axis=1)
train = train.drop(columns=['DayOfWeek'])

##### 훈련데이터 분리

In [34]:
from sklearn.model_selection import train_test_split
X = train.drop(columns=['Category']).to_numpy()
y = train.Category

x_train,x_tset,y_train,y_test = train_test_split(X,y,stratify=y,train_size=0.2,random_state=42)
# 그외에도 교차검증 방법이 있다. ^

x_train.shape, y_train.shape

y_train.value_counts()

Category
LARCENY/THEFT                  34980
OTHER OFFENSES                 25236
NON-CRIMINAL                   18461
ASSAULT                        15375
DRUG/NARCOTIC                  10794
VEHICLE THEFT                  10756
VANDALISM                       8945
WARRANTS                        8443
BURGLARY                        7351
SUSPICIOUS OCC                  6283
MISSING PERSON                  5198
ROBBERY                         4600
FRAUD                           3336
FORGERY/COUNTERFEITING          2122
SECONDARY CODES                 1997
WEAPON LAWS                     1711
PROSTITUTION                    1497
TRESPASS                        1465
STOLEN PROPERTY                  908
SEX OFFENSES FORCIBLE            877
DISORDERLY CONDUCT               864
DRUNKENNESS                      856
RECOVERED VEHICLE                627
KIDNAPPING                       468
DRIVING UNDER THE INFLUENCE      454
RUNAWAY                          389
LIQUOR LAWS                      381
ARSON                            303
LOITERING                        245
EMBEZZLEMENT                     233
SUICIDE                          102
FAMILY OFFENSES                   98
BAD CHECKS                        81
BRIBERY                           58
EXTORTION                         51
SEX OFFENSES NON FORCIBLE         30
GAMBLING                          29
PORNOGRAPHY/OBSCENE MAT            4
TREA                               1
Name: count, dtype: int64