####  감성분석 -> 머신러닝
데이터셋 : 전처리
- BoW 모델
    - 단어를 특성 벡터로 변환
    - tf-idf 단어 적합성 평가
    - 텍스트 데이터 정제
    - 문서를 토큰으로 나누기
- LogisticRegession

glob
    - 파이썬에서 파일 경로를 패턴(와일드카드)으로 검색할 때 사용하는 모듈
    - 특정 폴더 안에서 내가 원하는 형식의 파일만 찾아주는 역할을 합니다.
- 기본 개념
    - \* : 0개 이상의 임의의 문자
    - ? : 한 글자
    - [abc] : a, b, c 중 하나

데이터 사이트
http://ai.stanford.edu/~amaas/data/sentiment/aclImdb_v1.tar.gz

In [17]:
# 데이터 조회 : with, pd.DataFrame([]) , glob , concat
import pandas as pd
from glob import glob

# train_neg_df 생성
file_lists = glob("C:\\김지은\\데이터베이스\\aclImdb\\train\\neg\\*.txt")
pd_lists = []
for file_path in file_lists[:100]:
    with open(file_path,'r',encoding='utf-8') as f: 
        data ={
            'review' : f.read(),
            'target' : 0
        }
        df = pd.DataFrame([data])
        pd_lists.append(df)
train_neg_df = pd.concat(pd_lists,ignore_index=True)
train_neg_df.head()

# (x) : df = pd.DataFrame([f.read()]) # ([])
# 위 방법과 (x) 방법과의 차이

                                              review  target
0  Story of a man who has unnatural feelings for ...       0
1  Airport '77 starts as a brand new luxury 747 p...       0
2  This film lacked something I couldn't put my f...       0
3  Sorry everyone,,, I know this is supposed to b...       0
4  When I was little my parents took me along to ...       0

In [ ]:
# positive 동일하게 train_pos_df
# train_df = pd.concat([train_neg_df, train_pos_df])
# movie_data.csv

In [18]:
# train_pos_df 생성
file_lists = glob("C:\\김지은\\데이터베이스\\aclImdb\\train\\pos\\*.txt")
pd_lists = []
for file_path in file_lists[:100]:
    with open(file_path,'r',encoding='utf-8') as f: 
        data ={
            'review' : f.read(),
            'target' : 0
        }
        df = pd.DataFrame([data])
        pd_lists.append(df)
train_pos_df = pd.concat(pd_lists,ignore_index=True)
train_pos_df.head()

                                              review  target
0  Bromwell High is a cartoon comedy. It ran at t...       0
1  Homelessness (or Houselessness as George Carli...       0
2  Brilliant over-acting by Lesley Ann Warren. Be...       0
3  This is easily the most underrated film inn th...       0
4  This is not the typical Mel Brooks film. It wa...       0

In [ ]:
#
train_df = pd.concat([train_neg_df, train_pos_df])
train_df.head()

                                              review  target
0  Story of a man who has unnatural feelings for ...       0
1  Airport '77 starts as a brand new luxury 747 p...       0
2  This film lacked something I couldn't put my f...       0
3  Sorry everyone,,, I know this is supposed to b...       0
4  When I was little my parents took me along to ...       0

In [ ]:
pd.read_csv()